# Generated by Django 5.1.5 on 2025-02-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_chatsessionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
