# Generated by Django 5.1.5 on 2025-03-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userimageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyaimessage',
            name='add_time',
        ),
    ]
