# Generated by Django 5.1.5 on 2025-02-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_usericon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIcon',
        ),
    ]
