# Generated by Django 5.1.5 on 2025-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_userimageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
